### ISSUE TITLE
Error handling connection: invalid message?

### ISSUE THREAD

**Issue by MeztaGames** [TurboWarp/cloud-server#112]
I have been trying to get this to work for some time now but I always receive code 4000, and/or invalid room errors, why does this happen?
![image](https://user-images.githubusercontent.com/117587085/200191630-d965cf36-6dd0-4ec0-9387-461d2f17c85c.png)

**Comment by GarboMuffin** [comment]
"Invalid message" is caused by https://github.com/TurboWarp/cloud-server/blob/master/src/server.js#L42. So the client is sending a JSON value that isn't an object with a "method" property that is a string.

Room IDs are validated here: https://github.com/TurboWarp/cloud-server/blob/master/src/validators.js#L30. You can change it to be less restrictive if you want.

Adding logging in those places to see what's happening. I'm pretty sure this is a bug in whatever client you're using, not the server

**Comment by MeztaGames** [comment]
What exactly makes a room id invalid?

**Comment by GarboMuffin** [comment]
This is a cloud variable server, not a cloudlink server. My understand is that these are entirely unrelated.

Perhaps you can learn more here: https://github.com/meower-media-co/Meower-Vanilla

**Comment by MeztaGames** [comment]
I believe I have actually figured out the issue, it seems that if the packager packages a project from the official scratch website, no issues occur with connecting to a custom cloud server however if a project file from my computer were to be packaged I would always receive the error about the room id being invalid invalid, but I want to use a file from my computer to be packaged and to work with a cloud host, and not a project from the scratch website, how would I go about this issue?

**Comment by MeztaGames** [comment]
> "Invalid message" is caused by https://github.com/TurboWarp/cloud-server/blob/master/src/server.js#L42. So the client is sending a JSON value that isn't an object with a "method" property that is a string.
> 
> Room IDs (you might call these "project IDs") are validated here: https://github.com/TurboWarp/cloud-server/blob/master/src/validators.js#L30. You can change it to be less restrictive if you want. Our cloud variable server uses a modified version of this that doesn't verify that room IDs are numbers.
> 
> Code 4000 is a generic "you did something wrong that didn't violate the WebSocket protocol itself but did violate the cloud variable protocol"
> 
> Add logging in those places to see what's happening. I'm pretty sure this is a bug in whatever client you're using, not the server

I will be making it less restrictive so that it works with any string.

**Comment by GarboMuffin** [comment]
you can make the room ID check less picky here: https://github.com/TurboWarp/cloud-server/blob/master/src/validators.js#L30

just remove the `&& /^\d+$/.test(id);` part and it will allow anything.

**Comment by GarboMuffin** [comment]
and to clarify, you were experiencing two issues:

 - the default cloud-server is restricted to number room IDs only
 - you were trying to connect cloudlink to a cloud variable server
