### ISSUE TITLE
Invalid room ID

### ISSUE THREAD

**Issue by FallJuti** [TurboWarp/cloud-server#115]
<img width="746" alt="image" src="https://user-images.githubusercontent.com/110551762/202597777-8a013214-cf3d-434b-b5bc-c0c49b4820d3.png">
Sorry, I'm stupid
But I still don't know what happened

**Comment by GarboMuffin** [comment]
https://github.com/TurboWarp/cloud-server/blob/master/src/validators.js#L31

remove ` && /^\d+$/.test(id);` to let non-numeral project IDs work

**Comment by FallJuti** [comment]
Thank you
