### ISSUE TITLE
Cloud Variables with letters in value

### ISSUE THREAD

**Issue by Nintendero65pro** [TurboWarp/cloud-server#119]
We are making a game using TurboWarp and we self-hosted our own Cloud Variables server for the purpose of bypassing original's TurboWarp cloud server limitations, such as supporting tens of thousands of characters in a variable (which we bypassed successfully) and **using letters in value** but i cannot find a configuration to support letters.

**Comment by GarboMuffin** [comment]
https://github.com/TurboWarp/cloud-server/blob/master/src/validators.js#L52

**Comment by GarboMuffin** [comment]
you'll have to edit that function, probably the part after `  if (typeof value === 'string') {`, if that isn't clear. Perhaps just `return true;` after that.

**Comment by Nintendero65pro** [comment]
Thank you. 😁
