### ISSUE TITLE
WebSocket not connecting on mobile (iOS AND Android)

### ISSUE THREAD

**Issue by Dogo6647** [TurboWarp/cloud-server#124]
So I have my variable server set up like this:
(cloud-server) --> (Nginx for enabling https) --> (playit.gg "port forwarding" proxy)

And the Scratch project using that server was packaged using the TurboWarp Packager and then I added the files into this repository so that I could deploy it to a github page: https://github.com/Dogo6647/blabble-pwa-mobile

So when I go into that github page using any PC web browser, it works just fine, everything works as expected. But when I connect using any mobile device, I get an error from the developer console with absolutely no useful information at all.

The https certificate is self-signed BTW, I'm pretty sure that's the problem. Either that, or the port needs to be 443 (I can't change the port since I use playit.gg). Also, if the culprit IS the self-signed certificate, please tell me how to set up a Let's Encrypt certificate, I have close-to-zero experience with web servers.

**Comment by GarboMuffin** [comment]
> The https certificate is self-signed BTW

That is the problem

SSL is left as an exercise to the user. Perhaps you may want to start at https://letsencrypt.org/getting-started/

**Comment by Dogo6647** [comment]
Thanks I guess, how silly of me, I guess I just had to read the instructions for Let's Encrypt carefully before deciding to do a self-sign. Sorry about that.
