### ISSUE TITLE
Game wont connect to cloud 

### ISSUE THREAD

**Issue by Cuphead74832** [TurboWarp/cloud-server#131]
(Contacted with contact@turbowarp.org) I made a remix and made a stupid versión of an among us Game by TimMcCool (check Project LT on my GitHub) and It wont connect to public and private server. Wonder if you guys could Check it.
https://github.com/Cuphead74832/Project-socolsocnort

**Comment by GarboMuffin** [comment]
set the username back to player####

**Comment by Cuphead74832** [comment]
Will try due to recompiling everything Will be bad for me due to bad internet issues modifying the Index.html file instead

**Comment by Cuphead74832** [comment]
Worked!!!

**Comment by Cuphead74832** [comment]
> set the username back to player####

Should have read the packager warning.
