### ISSUE TITLE
Question: Does cloud variable get stored permanently?

### ISSUE THREAD

**Issue by Cuphead74832** [TurboWarp/cloud-server#132]
Example if multiple clients are connected the cloud store and share the value but if all client disconnects after a while Will cloud reset?? Or i have to write a project to set all to 0?

**Comment by GarboMuffin** [comment]
They get reset when no one is connected for a little bit

**Comment by Cuphead74832** [comment]
> They get reset when no one is connected for a little bit

THX i just received the SSD i wanted for that old laptop and im gonna host my local cloud.
