### ISSUE TITLE
How to use thirdparty cloud server in cloud-variables-anywhere？

### ISSUE THREAD

**Issue by 0832k12** [TurboWarp/cloud-server#135]
![image](https://github.com/TurboWarp/cloud-server/assets/70421730/89dff540-b7ad-4751-b7b5-ea519b133a84)
connect is disabled.

**Comment by 0832k12** [comment]
And connect to `wss://0832.ink/tw-clouddata` is enabled.

**Comment by 0832k12** [comment]
![image](https://github.com/TurboWarp/cloud-server/assets/70421730/74cad449-c5a7-4712-8070-0f17f7a9df7f)

**Comment by GarboMuffin** [comment]
Your web server is not set up to handle WebSocket connections properly. Notice that the error is from your browser, not from us. 301 redirects are not compatible with WebSockets and are unlikely to help bypass censorship, if that's what you're trying to do.

**Comment by GarboMuffin** [comment]
```js
ws = new WebSocket('wss://0832.ink/tw-clouddata')
```

**Comment by GarboMuffin** [comment]
https://www.google.com/search?hl=en&q=nginx%20websocket

**Comment by 0832k12** [comment]
Thanks!
