### ISSUE TITLE
How to keep online variables forever in disk and have letters

### ISSUE THREAD

**Issue by Piratefoxy216** [TurboWarp/cloud-server#94]
Example: saving data then leaving, and then coming back and the data is still there saved in the local disk.

Example 2: being able to type letters to cloud aka local disk.

**Comment by GarboMuffin** [comment]
You can use something like https://github.com/SheepTester/primitive-cloud-server instead. This cloud server is designed to do what clouddata.turbowarp.org needs and nothing more.

**Comment by Piratefoxy216** [comment]
Thank you GarboMuffin!
